create table document
(
    id            bigint generated by default as identity,
    doc_type      varchar(127) not null,
    organization  varchar(255) not null,
    description   varchar(512) not null,
    creation_date date         not null,
    patient       varchar(255) not null,
    status        varchar(20)  not null,
    constraint pk_document primary key (id)
);

create table outbox
(
    id      bigint generated by default as identity,
    payload text not null,
    is_sent bool not null default false,
    constraint pk_outbox primary key (id)
);

create table inbox
(
    id      bigint,
    payload bytea not null,
    is_read bool  not null,
    constraint pk_inbox primary key (id)
);